spring.application.name=petvitta

# Desativa o cache do Thymeleaf para atualizar o HTML na hora
spring.thymeleaf.cache=false

# Desativa o cache de recursos estáticos (CSS e JS)
spring.web.resources.cache.period

# Banco de dados
# Conecta ao banco de dados
spring.datasource.url=jdbc:mysql://localhost:3306/petvitta 
spring.datasource.username=root
spring.datasource.password=Vivi182023

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true